AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Lupin: CFN Template to create a EC2 security group with rules

Metadata:
  TemplateName: security-group-stack.yaml
  TemplateType: Security Group to allow ICMP.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Lupin
  Last Modified: Jun 21, 2024
  Resources: 
    - One EC2 security group to allow ICMP traffic
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### Security Group ############################################
    - Label:
        default: "Security Group Parameters"
      Parameters: 
      - VpcId
      - EnableIPV6Cidr
      - EC2SecurityGroupBaseName
      - EC2SecurityGroupDescription
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      ################################## Security Group ############################################
      VpcId:
        default: "VPC Id where the EC2 security group will to be created."
      EnableIPV6Cidr: 
        default: "Enable IPV6 Cidr."
      EC2SecurityGroupBaseName:
        default: "EC2 security group name."
      EC2SecurityGroupDescription:
        default: "EC2 security group description."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: lupin
    Description: "The project name that will be used as resource name prefixes and will be used to tag resources to track the project cost."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The deployment environment (dev/test/prod)."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub ref name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The GitHub workflow run number for the latest CI/CD pipeline."
    Type: Number
  GitHubSHA:
    Default: "27e994ee4b064c37170c9a702c44b676c3295e1f"
    Description: "The sha value of the last commit."
    Type: String
  GitHubRepository:
    Default: 0104-lupin-cft
    Description: "The GitHub repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### Security Group ############################################
  VpcId: 
    Description: The VPC Id where the Lambda security group will be created.
    Type: AWS::EC2::VPC::Id
  EnableIPV6Cidr:
    Default: "False"
    Description: "Enable IPV6 Cidr ?"
    Type: String
    AllowedValues:
    - "True"
    - "False"
  EC2SecurityGroupBaseName:
    Default: ec2-sg
    Description: "EC2 security group base name."
    Type: String
    MinLength: 3
    MaxLength: 10
    AllowedPattern: "[a-z0-9-]*"
  EC2SecurityGroupDescription:
    Default: "EC2 Security Group"
    Description: "EC2 security group description."
    Type: String
    MinLength: 10
    MaxLength: 50
    AllowedPattern: "[a-zA-Z0-9 .-]*"

######################################## Conditions ################################################
Conditions:
  EnableIPV6Cidr: !Equals [!Ref EnableIPV6Cidr, "True"]
Resources:
  ###################################### EC2 Security Group ########################################
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EC2SecurityGroupBaseName}-${AWS::Region}${CiBuild}'
      GroupDescription: !Ref EC2SecurityGroupDescription
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EC2SecurityGroupBaseName}-${Environment}-${AWS::Region}${CiBuild}'
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
  ###################################### EC2 Security Group Rules ##################################
  SecGroupRuleICMPIPV4:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt EC2SecurityGroup.GroupId
      IpProtocol: icmp
      FromPort: -1
      ToPort: -1
      CidrIp: "0.0.0.0/0"
      Description: "Open up ports for ICMP IPV4"
  SecGroupRuleICMPIPV6:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: EnableIPV6Cidr
    Properties:
      GroupId: !GetAtt EC2SecurityGroup.GroupId
      IpProtocol: icmp
      FromPort: -1
      ToPort: -1
      CidrIpv6: "::/0"
      Description: "Open up ports for ICMP IPV6"
Outputs:
  EC2SecurityGroupId:
    Description: EC2 Security Group Id
    Value: !GetAtt EC2SecurityGroup.GroupId
  EC2SecurityGroupVpcId:
    Description: VPC Id of EC2 Security Group
    Value: !GetAtt EC2SecurityGroup.VpcId


